export const ProductData = [
   {
      img:"./images/p1.png",
      id:1,
      dec: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
      price: "9,999",
      discount: "30%",
      rating: "4.2 of 5",
   },
   {
      img:"./images/p2.png",
      id:2,
      dec: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
      price: "8,999",
      discount: "50%",
      rating: "3.2 of 5",
   },
   {
      img:"./images/p3.png",
      id:3,
      dec: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
      price: "4,999",
      discount: "30%",
      rating: "7.2 of 5",
   },
   {
      img:"./images/p4.png",
      id:4,
      dec: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
      price: "9,999",
      discount: "30%",
      rating: "3.2 of 5",
   },
   {
      img:"./images/p1.png",
      id:6,
      dec: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
      price: "6,999",
      discount: "40%",
      rating: "2.2 of 5",
   },
   {
      img:"./images/p2.png",
      id:7,
      dec: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
      price: "3,999",
      discount: "40%",
      rating: "2.2 of 5",
   },
   {
      img:"./images/p3.png",
      id:8,
      dec: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
      price: "5,999",
      discount: "40%",
      rating: "2.2 of 5",
   },

];